version: '3.8'

services:
  eva:
    build:
      context: .
      dockerfile: Dockerfile
    image: eva-monorepo:latest
    container_name: eva
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    # Uncomment and configure if you need to pass environment variables
    # env_file:
    #   - apps/backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
